export const ADD_NOTEBOOK = 'ADD_NOTEBOOK';

export const ADD_NOTEBOOK_PENDING = ADD_NOTEBOOK + '_PENDING';

export const ADD_NOTEBOOK_FULFILLED = ADD_NOTEBOOK + '_FULFILLED';

export const ADD_NOTEBOOK_REJECTED = ADD_NOTEBOOK + '_REJECTED';

export const UPDATE_NOTEBOOK = 'UPDATE_NOTEBOOK';

export const UPDATE_NOTEBOOK_PENDING = UPDATE_NOTEBOOK + '_PENDING';

export const UPDATE_NOTEBOOK_FULFILLED = UPDATE_NOTEBOOK + '_FULFILLED';

export const UPDATE_NOTEBOOK_REJECTED = UPDATE_NOTEBOOK + '_REJECTED';

export const REMOVE_NOTEBOOK = 'REMOVE_NOTEBOOK';

export const REMOVE_NOTEBOOK_PENDING = REMOVE_NOTEBOOK + '_PENDING';

export const REMOVE_NOTEBOOK_FULFILLED = REMOVE_NOTEBOOK + '_FULFILLED';

export const REMOVE_NOTEBOOK_REJECTED = REMOVE_NOTEBOOK + '_REJECTED';

export const GET_NOTEBOOKS = 'GET_NOTEBOOKS';

export const GET_NOTEBOOKS_PENDING = GET_NOTEBOOKS + '_PENDING';

export const GET_NOTEBOOKS_FULFILLED = GET_NOTEBOOKS + '_FULFILLED';

export const GET_NOTEBOOKS_REJECTED = GET_NOTEBOOKS + '_REJECTED';
