export const ADD_NOTES = 'ADD_NOTES';

export const ADD_NOTES_PENDING = ADD_NOTES + '_PENDING';

export const ADD_NOTES_FULFILLED = ADD_NOTES + '_FULFILLED';

export const ADD_NOTES_REJECTED = ADD_NOTES + '_REJECTED';

export const UPDATE_NOTES = 'UPDATE_NOTES';

export const UPDATE_NOTES_PENDING = UPDATE_NOTES + '_PENDING';

export const UPDATE_NOTES_FULFILLED = UPDATE_NOTES + '_FULFILLED';

export const UPDATE_NOTES_REJECTED = UPDATE_NOTES + '_REJECTED';

export const REMOVE_NOTES = 'REMOVE_NOTES';

export const REMOVE_NOTES_PENDING = REMOVE_NOTES + '_PENDING';

export const REMOVE_NOTES_FULFILLED = REMOVE_NOTES + '_FULFILLED';

export const REMOVE_NOTES_REJECTED = REMOVE_NOTES + '_REJECTED';

export const MOVE_TO_NOTEBOOK = 'MOVE_TO_NOTEBOOK';

export const MOVE_TO_NOTEBOOK_PENDING = MOVE_TO_NOTEBOOK + '_PENDING';

export const MOVE_TO_NOTEBOOK_FULFILLED = MOVE_TO_NOTEBOOK + '_FULFILLED';

export const MOVE_TO_NOTEBOOK_REJECTED = MOVE_TO_NOTEBOOK + '_REJECTED';

export const GET_NOTES = 'GET_NOTES';

export const GET_NOTES_PENDING = GET_NOTES + '_PENDING';

export const GET_NOTES_FULFILLED = GET_NOTES + '_FULFILLED';

export const GET_NOTES_REJECTED = GET_NOTES + '_REJECTED';

export const REPLACE_NOTEBOOKS_FROM_NOTES = 'REPLACE_NOTEBOOKS_FROM_NOTES';

export const REPLACE_NOTEBOOKS_FROM_NOTES_PENDING = REPLACE_NOTEBOOKS_FROM_NOTES + '_PENDING';

export const REPLACE_NOTEBOOKS_FROM_NOTES_FULFILLED = REPLACE_NOTEBOOKS_FROM_NOTES + '_FULFILLED';

export const REPLACE_NOTEBOOKS_FROM_NOTES_REJECTED = REPLACE_NOTEBOOKS_FROM_NOTES + '_REJECTED';
